name: tf-checks
permissions:
  id-token: write
on:
  pull_request:
jobs:
  basic:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@master
    with:
      working_directory: './examples/basic/'
      provider: aws
    secrets: 
      BUILD_ROLE: ${{ secrets.BUILD_ROLE }}
  complete:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@master
    with:
      working_directory: './examples/complete/'
      provider: aws
    secrets: 
      BUILD_ROLE: ${{ secrets.BUILD_ROLE }}

