name: tfsec
on:
  pull_request:

#jobs:
#  tfsec:
#    name: tfsec sarif report
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Clone repo
#        uses: actions/checkout@master

jobs:
  tfsec:
    name: tfsec
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Terraform security scan
        uses: triat/terraform-security-scan@v3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



#      - name: tfsec
#        uses: aquasecurity/tfsec-sarif-action@v0.1.0
#        if: github.event_name == 'pull_request'
#        with:
#          GITHUB_TOKEN: ${{ secrets.TOKEN }}
#          soft_fail: true
#          sarif_file: tfsec.sarif
#          working_directory: _example
#          tfsec_actions_comment: true
#          full_repo_scan: true
#          tfsec_output_format: sarif
#          continue-on-error: true


      - name: tfsec
        uses: aquasecurity/tfsec-sarif-action@v0.1.3
        with:
          sarif_file: tfsec.sarif
          working_directory: _example/
          full_repo_scan: true
#          tfvars_file: main.tf

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
           # Path to SARIF file relative to the root of the repository
           sarif_file: tfsec.sarif



#      - name: tfsec
#        uses: triat/terraform-security-scan@master
#        if: github.event_name == 'pull_request'
#        env:
#          GITHUB_TOKEN: ${{ secrets.TOKEN }}
#          tfsec_actions_working_dir: ./_example
#          tfsec_actions_comment: true
#          tfsec_output_format: sarif
#          continue-on-error: true

#      - name: 'Setup tfsec Basic'
#        uses: aquasecurity/tfsec-action@v1.0.0
#        with:
#          soft_fail: true
#          working_directory: ./terraform/prod

#
#      - name: Upload SARIF file
#        uses: github/codeql-action/upload-sarif@v1
#        with:
#          # Path to SARIF file relative to the root of the repository
#          sarif_file: tfsec.sarif

