name: "Use Shared Stale Workflow"

on:
  workflow_dispatch:
  push:

jobs:
  stale:
    uses: clouddrove/github-shared-workflows/.github/workflows/stale.yml@1.4.1
    secrets:
      repo-token: ${{ secrets.GITHUB_TOKEN }}
