name: "Use Shared Stale Workflow"

on:
  workflow_dispatch:
  push:

jobs:
  stale:
    uses: clouddrove/github-shared-workflows/.github/workflows/pr-stale.yml@main
    secrets:
      repo-token: ${{ secrets.GITHUB_TOKEN }}
