name: 'Call Shared Workflow to Validate PR Title'

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  validate-title:
    uses: clouddrove/github-shared-workflows/.github/workflows/validate-pr-title.yml@1.4.1
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
